---
# tasks file for DatabaseSetup

### MYSQL

# Make users
  - name: Add new local database user for cowrie
    mysql_user:
      login_user: 'root'
      login_password: ''
      login_unix_socket: '/var/run/mysqld/mysqld.sock'
      name: '{{ mysql_user }}'
      password: '{{ mysql_user_password }}'
      priv: '{{ mysql_database }}.*:ALL,GRANT'
      state: present
    become: true

  - name: Add new remote database user for cowrie
    mysql_user:
      login_user: 'root'
      login_password: ''
      login_unix_socket: '/var/run/mysqld/mysqld.sock'
      name: '{{ mysql_user }}'
      password: '{{ mysql_user_password }}'
      priv: '{{ mysql_database }}.*:ALL,GRANT'
      host: '{{ grafana_server }}'
      state: present
    become: true

  - name: Remove root database user
    mysql_user:
      login_user: 'root'
      login_password: ''
      login_unix_socket: '/var/run/mysqld/mysqld.sock'
      name: 'root'
      host_all: yes
      state: absent
    become: true

# Fix encoding issue
  - name: Change charset in Cowrie python script
    lineinfile:
      path: /home/cowrie/cowrie/src/cowrie/output/mysql.py
      regexp: 'charset="utf8mb4"'
      line: 'charset="utf8",'
    become: true

# Make database + config
  - name: Install Cowrie database
    become_user: cowrie
    mysql_db:
      login_user: '{{ mysql_user }}'
      login_password: '{{ mysql_user_password }}'
      name: '{{ mysql_database }}'
      state: import
      target: /home/cowrie/cowrie/docs/sql/mysql.sql
    become: true

  - name: Edit config to set cowrie login for database
    become_user: cowrie
    lineinfile:
      path: /home/cowrie/cowrie/etc/cowrie.cfg
      firstmatch: yes
      regexp: '^password = secret'
      insertafter: '\\[output_mysql\\]'
      line: 'password = {{ mysql_user_password }}'
      state: present
    become: true

  - name: Edit config to set database port
    become_user: cowrie
    lineinfile:
      path: /home/cowrie/cowrie/etc/cowrie.cfg
      firstmatch: yes
      insertafter: '\\[output_mysql\\]'
      regexp: '^port = 3306'
      line: 'port = {{ mysql_port }}'
      state: present
    become: true

  - name: Remove disable logging
    become_user: cowrie
    lineinfile:
      path: /home/cowrie/cowrie/etc/cowrie.cfg
      firstmatch: yes
      regexp: '^enabled = false'
      insertafter: '\\[output_mysql\\]'
      state: absent
    become: true

  - name: Enable mysql logging
    become_user: cowrie
    lineinfile:
      path: /home/cowrie/cowrie/etc/cowrie.cfg
      firstmatch: yes
      regexp: '^debug = false'
      insertafter: '\\[output_mysql\\]'
      line: 'enabled = true'
      state: present
    become: true

  - name: Change mysql bind-address
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
    become: true

  - name: Change mysql port
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^port'
      line: 'port = {{ mysql_port }}'
    become: true
    notify:
      - Restart MariaDB

  - name: Flush handlers
    meta: flush_handlers

